-- Schema base para app de eventos con roles en Supabase

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc', now())
);

create table if not exists public.eventos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descripcion text not null,
  fecha date not null,
  precio numeric(10,2) not null check (precio > 0),
  limite_boletos integer not null check (limite_boletos > 0),
  created_at timestamp with time zone default timezone('utc', now())
);


create table if not exists public.stripe_sessions_procesadas (
  session_id text primary key,
  processed_at timestamp with time zone default timezone('utc', now())
);

create table if not exists public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  rol text not null check (rol in ('superusuario', 'usuario')),
  created_at timestamp with time zone default timezone('utc', now())
);

alter table public.usuarios enable row level security;
alter table public.eventos enable row level security;
alter table public.perfiles enable row level security;

-- Inserta perfil "usuario" automáticamente cuando alguien se registra en auth.users
create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.perfiles (id, rol)
  values (new.id, 'usuario')
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
  after insert on auth.users
  for each row execute procedure public.handle_new_user_profile();

-- Helper para evaluar si el usuario autenticado es superusuario
create or replace function public.is_superuser()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.perfiles
    where id = auth.uid() and rol = 'superusuario'
  );
$$;


-- Descuenta boletos en forma atómica para evitar sobreventa
create or replace function public.descontar_boletos(p_evento_id bigint, p_cantidad integer)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_stock integer;
begin
  if p_cantidad <= 0 then
    return false;
  end if;

  select limite_boletos into current_stock
  from public.eventos
  where id = p_evento_id
  for update;

  if current_stock is null then
    return false;
  end if;

  if current_stock < p_cantidad then
    return false;
  end if;

  update public.eventos
  set limite_boletos = limite_boletos - p_cantidad
  where id = p_evento_id;

  return true;
end;
$$;

-- Reinicia políticas para que el script sea re-ejecutable
-- Usuarios
drop policy if exists "usuarios_select_self" on public.usuarios;
drop policy if exists "usuarios_insert_self" on public.usuarios;

-- Perfiles
drop policy if exists "perfil_select_self" on public.perfiles;
drop policy if exists "perfil_insert_self" on public.perfiles;
drop policy if exists "perfil_update_self" on public.perfiles;

-- Eventos
drop policy if exists "eventos_select_authenticated" on public.eventos;
drop policy if exists "eventos_insert_superuser" on public.eventos;
drop policy if exists "eventos_update_superuser" on public.eventos;
drop policy if exists "eventos_delete_superuser" on public.eventos;

-- Políticas base para usuarios (tabla pública de registro administrativo)
create policy "usuarios_select_self" on public.usuarios
for select
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

create policy "usuarios_insert_self" on public.usuarios
for insert
with check (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

-- Políticas base para perfiles
create policy "perfil_select_self" on public.perfiles
for select
using (auth.uid() = id);

create policy "perfil_insert_self" on public.perfiles
for insert
with check (auth.uid() = id);

create policy "perfil_update_self" on public.perfiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- Políticas de eventos
-- Cualquier usuario autenticado puede ver eventos
create policy "eventos_select_authenticated" on public.eventos
for select
using (auth.uid() is not null);

-- Solo superusuario puede crear/editar/eliminar eventos
create policy "eventos_insert_superuser" on public.eventos
for insert
with check (public.is_superuser());

create policy "eventos_update_superuser" on public.eventos
for update
using (public.is_superuser())
with check (public.is_superuser());

create policy "eventos_delete_superuser" on public.eventos
for delete
using (public.is_superuser());

-- Cambia TU cuenta a superusuario manualmente.
-- Sustituye el email por el tuyo y ejecútalo una sola vez.
update public.perfiles p
set rol = 'superusuario'
from auth.users u
where p.id = u.id
  and lower(u.email) = lower('tu-correo-superusuario@dominio.com');
